### PR TITLE
Bug template changes

### PR DESCRIPTION
**Pull request by pat-s**
@sebffischer 

LMK if you have questions about specific changes.

### CODE REVIEW

**Comment by sebffischer** [comment]
One thing is unclear as is I think. When calling `reprex::reprex()`, the code is copied to the clipboard automatically, here it sounds as if one has to copy it from the browser

**Comment by pat-s** [comment]
In most cases but not all. In remote sessions reprex does not always has access to the clipboard, in these cases the output is written to a file which then needs to be copied manually.

**Comment by sebffischer** [comment]
Ah I didn't know that.

**Comment by sebffischer** [comment]
Should we merge?

**Comment by pat-s** [comment]
Sure, was waiting for you :)

**Pull request merged**
