### PR TITLE
Template

### PR DESCRIPTION
**Pull request by sebffischer**

### CODE REVIEW

**Comment by pfistfl** [comment]
You could add something like 
- Which mlr3 packages other than mlr3 are  you using (e.g. mlr3pipelines, mlr3proba) ?

Change
Please give all relevant information below for bug reports. to
Please provide all relevant information for bug reports below.

**Review by pat-s — COMMENTED** [review]
Thanks!

Here are some possible improvements:

1. Tell explicitlcy that users should call `update.packages()`
2. Can be left out I think - good intentions but I guess this line won't really have an effect
3. We could provide links to https://mlr-org.com/tasks.html and add a line of `task = tsk("<example task")` or similar
4. Remove "try to raise" and something like "please think again if your issue is really related to mlr3 itself or one of the mlr3verse packages (e.g. mlr3tuning, mlr3learners, etc)

Can we inject example code how to create a reprex in the boxes? I.e. paste a little snipped that shows a `reprex::reprex()` call?

The session info field can be omitted I think, we should encourage people to use `reprex(session_info = TRUE)`.

I am a fan of GH discussions to keep GH Issues "question free". Should we incentivize people to ask their questions there rather than opening an issue?

**Comment by sebffischer** [comment]
we can link here https://stackoverflow.com/help/minimal-reproducible-example

**Comment by pat-s** [comment]
> we can link here [stackoverflow.com/help/minimal-reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example)

This is great and should certainly be included - I wonder though if we can just include a little direct example of maybe 5 lines in the issue form - so that new users directly understand how to do it?

**Comment by sebffischer** [comment]
I don't think we should overload the issue template with tutorials but rather link to other resources? 

This is the current version:
https://github.com/sebffischer/test/issues/new/choose

**Comment by pat-s** [comment]
Not overload - just provide some sample code. `reprex::reprex(..., session_info = TRUE)` is already a good start!

My experience is that simply linking to {reprex} or saying "please use it" does often not help - especially not for the people who c/p without formatting or similar. They usually don't know what they do (in many cases) and can't infer how to use {reprex}.

I'll do a PR with what I mean.

On the side, do we really want to link to our MM here? Questions asked there are not findable on the web and I think discussions there should always be based on an existing issue - i.e. if chat-discussion is needed. I would not point people to MM for opening/asking Qs in the first place. Having MM linked in various places is certainly what we want but in this specific issue template case, I'd rather avoid it. Instead I'd link to the stackoverflow tag?

**Comment by sebffischer** [comment]
https://github.com/sebffischer/test/issues/new/choose

Good points, I adjusted it. If you have no more suggestions I would merge it

**Comment by pat-s** [comment]
Thanks! I still have some idea/corrections, I'll apply do them later this evening 🙂

**Pull request merged**
